// Re-export ProgramInput from ethrex guest_program
// This allows us to use the same input format as ethrex, ensuring compatibility
// with the ExecutionWitness generation and stateless validation logic.

pub use guest_program::input::ProgramInput as UniEvmProgramInput;

// The ProgramInput structure from ethrex contains:
// - blocks: Vec<Block> - Blocks to execute
// - execution_witness: ExecutionWitness - State data for stateless execution
// - elasticity_multiplier: u64 - EIP-1559 base fee calculation
// - fee_configs: Option<Vec<FeeConfig>> - L2 fee configs per block
// - blob_commitment: [u8; 48] - KZG commitment to blob data (unused in uni-evm)
// - blob_proof: [u8; 48] - KZG opening proof (unused in uni-evm)
//
// For uni-evm:
// - We always use blocks.len() == 1 (per-block proving)
// - blob_commitment and blob_proof are set to [0; 48] (no blob data)
// - fee_configs can be Some(vec![FeeConfig::default()])
// - execution_witness is generated by blockchain.generate_witness_for_blocks()
